@startuml
'https://plantuml.com/class-diagram


interface BotPlayingStrategy{
    int getPosition(GameBoard board)
}

class EasyBot implements BotPlayingStrategy{
}

class MediumBot implements BotPlayingStrategy{
}

interface WinningStrategy{
  boolean checkIfCurrentPlayerIsWinner(GameBoard board, int rowPos, int colPos, String symbol)
}

class RowWinningStrategy implements WinningStrategy{}

class ColumnWinningStrategy implements WinningStrategy{}

interface Player{
    makeMove(int position)
}

class Human implements Player{
    String email
    String name
    String profilePicture
    String symbol
    makeMove(int position)
}

enum DifficultyLevel{
EASY
MEDIUM
HARD
}

enum MatchState{
    IN_PROGRESS
    WIN
    DRAW
}

class Bot implements Player{
    DifficultyLevel difficultylevel
    String symbol
    makeMove(int position)
}

class Match{
    MatchState matchState
    List<Player> players
    List<List<String>> gameBoard
    int dimension

    play()
}


@enduml